[mypy]
python_version = 3.11
python_executable = $MYPY_CONFIG_FILE_DIR/.venv/bin/python
mypy_path = $MYPY_CONFIG_FILE_DIR/packages/lucid/src,$MYPY_CONFIG_FILE_DIR/packages/lucid-host/src,$MYPY_CONFIG_FILE_DIR/packages/lucid-modal/src,$MYPY_CONFIG_FILE_DIR/packages/lucid-dev/src,$MYPY_CONFIG_FILE_DIR/examples/waypoint_modal/src,$MYPY_CONFIG_FILE_DIR/examples/helios_modal/src,$MYPY_CONFIG_FILE_DIR/examples/yume_modal/src
explicit_package_bases = True
namespace_packages = True
warn_unused_configs = True
exclude = (^\.venv/|^target/|.*/\.venv/|.*/build/|.*/dist/)
