coordinator:
  image:
    repository: lucid/coordinator
    tag: dev
    pullPolicy: IfNotPresent

worker:
  enabled: false
  image:
    repository: lucid/worker
    tag: dev
    pullPolicy: IfNotPresent
