from __future__ import annotations

import json
import os
import re
import sys
import importlib
from pathlib import Path
from typing import Any


ROOT = Path(__file__).resolve().parent.parent
LUCID_SRC = ROOT / "packages" / "lucid" / "src"
YUME_MODAL_EXAMPLE_SRC = ROOT / "examples" / "yume_modal" / "src"
WAYPOINT_MODAL_EXAMPLE_SRC = ROOT / "examples" / "waypoint_modal" / "src"
MANIFEST_PATH = ROOT / "packages" / "contracts" / "generated" / "lucid_manifest.json"
WAYPOINT_MANIFEST_PATH = (
    ROOT / "packages" / "contracts" / "generated" / "lucid_manifest.waypoint.json"
)
TS_PATH = ROOT / "apps" / "demo" / "src" / "lib" / "generated" / "lucid.ts"


def main() -> int:
    sys.path.insert(0, str(LUCID_SRC))
    yume_manifest = _load_manifest(
        module_name="yume_modal_example.model",
        extra_path=YUME_MODAL_EXAMPLE_SRC,
    )
    waypoint_manifest = _load_manifest(
        module_name="waypoint_modal_example.model",
        extra_path=WAYPOINT_MODAL_EXAMPLE_SRC,
    )
    MANIFEST_PATH.parent.mkdir(parents=True, exist_ok=True)
    MANIFEST_PATH.write_text(
        json.dumps(yume_manifest, indent=2, sort_keys=True) + "\n",
        encoding="utf-8",
    )
    WAYPOINT_MANIFEST_PATH.write_text(
        json.dumps(waypoint_manifest, indent=2, sort_keys=True) + "\n",
        encoding="utf-8",
    )
    TS_PATH.parent.mkdir(parents=True, exist_ok=True)
    TS_PATH.write_text(render_ts(yume_manifest), encoding="utf-8")
    return 0


def _load_manifest(*, module_name: str, extra_path: Path) -> dict[str, Any]:
    if str(extra_path) not in sys.path:
        sys.path.insert(0, str(extra_path))

    previous_model_module = os.environ.get("WM_MODEL_MODULE")
    previous_model_name = os.environ.get("WM_MODEL_NAME")
    os.environ["WM_MODEL_MODULE"] = module_name
    os.environ["WM_MODEL_NAME"] = module_name.split(".", 1)[0].replace("_modal_example", "")
    capabilities = importlib.import_module("lucid.capabilities")
    try:
        capabilities.ensure_model_module_loaded()
        return capabilities.manifest()
    finally:
        if previous_model_module is None:
            os.environ.pop("WM_MODEL_MODULE", None)
        else:
            os.environ["WM_MODEL_MODULE"] = previous_model_module
        if previous_model_name is None:
            os.environ.pop("WM_MODEL_NAME", None)
        else:
            os.environ["WM_MODEL_NAME"] = previous_model_name


def render_ts(manifest: dict[str, Any]) -> str:
    action_interfaces: list[str] = []
    action_map_lines: list[str] = []
    action_names: list[str] = []
    for action in manifest.get("actions", []):
        name = str(action["name"])
        action_names.append(name)
        interface_name = _interface_name(name)
        action_interfaces.append(
            f"export interface {interface_name} {render_object_schema(action.get('args_schema', {}))}"
        )
        action_map_lines.append(f'  "{name}": {interface_name}')

    manifest_json = json.dumps(manifest, indent=2, sort_keys=True)
    action_name_union = " | ".join(f'"{name}"' for name in action_names) or "never"
    return "\n".join(
        [
            "// This file is @generated by scripts/generate_lucid_artifacts.py.",
            "// Do not edit it by hand.",
            "",
            f"export const lucidManifest = {manifest_json} as const",
            "",
            *action_interfaces,
            "",
            "export interface ActionArgumentsByName {",
            *action_map_lines,
            "}",
            "",
            f"export type ActionName = {action_name_union}",
            "",
            "export interface ActionEnvelope<TName extends ActionName = ActionName> {",
            '  type: "action"',
            "  seq: number",
            "  ts_ms: number",
            "  session_id: string | null",
            "  payload: {",
            "    name: TName",
            "    args: ActionArgumentsByName[TName]",
            "  }",
            "}",
            "",
            "const encoder = new TextEncoder()",
            "",
            "export function encodeActionMessage<TName extends ActionName>(args: {",
            "  name: TName",
            "  args: ActionArgumentsByName[TName]",
            "  seq: number",
            "  sessionId: string",
            "}) {",
            "  const envelope: ActionEnvelope<TName> = {",
            '    type: "action",',
            "    seq: args.seq,",
            "    ts_ms: Date.now(),",
            "    session_id: args.sessionId,",
            "    payload: {",
            "      name: args.name,",
            "      args: args.args,",
            "    },",
            "  }",
            "  return encoder.encode(JSON.stringify(envelope))",
            "}",
            "",
        ]
    )


def render_object_schema(schema: dict[str, Any]) -> str:
    properties = schema.get("properties", {})
    required = set(schema.get("required", []))
    lines = ["{"]
    for key, value in properties.items():
        optional = "" if key in required else "?"
        lines.append(f"  {json.dumps(key)}{optional}: {_ts_type(value)}")
    lines.append("}")
    return "\n".join(lines)


def _ts_type(schema: dict[str, Any]) -> str:
    schema_type = schema.get("type")
    if isinstance(schema_type, list):
        return " | ".join(
            sorted(
                _ts_type({"type": item, **{k: v for k, v in schema.items() if k != "type"}})
                for item in schema_type
            )
        )
    if schema_type == "string":
        enum_values = schema.get("enum")
        if enum_values:
            return " | ".join(json.dumps(value) for value in enum_values)
        return "string"
    if schema_type in {"number", "integer"}:
        return "number"
    if schema_type == "boolean":
        return "boolean"
    if schema_type == "array":
        return f"{_ts_type(schema.get('items', {}))}[]"
    if schema_type == "null":
        return "null"
    return "Record<string, unknown>"


def _interface_name(action_name: str) -> str:
    sanitized = re.sub(r"[^A-Za-z0-9]+", " ", action_name)
    parts = [part for part in sanitized.split() if part]
    return "".join(part[:1].upper() + part[1:] for part in parts) + "Args"


if __name__ == "__main__":
    raise SystemExit(main())
