from __future__ import annotations

import json
import re
import sys
import importlib
from pathlib import Path
from typing import Any


ROOT = Path(__file__).resolve().parent.parent
LUCID_PKG = ROOT / "packages" / "lucid"
YUME_MODAL_EXAMPLE_SRC = ROOT / "examples" / "yume_modal" / "src"
WAYPOINT_MODAL_EXAMPLE_SRC = ROOT / "examples" / "waypoint_modal" / "src"
HELIOS_MODAL_EXAMPLE_SRC = ROOT / "examples" / "helios_modal" / "src"
MANIFEST_PATH = ROOT / "packages" / "contracts" / "generated" / "lucid_manifest.json"
WAYPOINT_MANIFEST_PATH = (
    ROOT / "packages" / "contracts" / "generated" / "lucid_manifest.waypoint.json"
)
HELIOS_MANIFEST_PATH = (
    ROOT / "packages" / "contracts" / "generated" / "lucid_manifest.helios.json"
)
TS_PATH = ROOT / "apps" / "demo" / "src" / "lib" / "generated" / "lucid.ts"
WAYPOINT_TS_PATH = (
    ROOT / "apps" / "demo" / "src" / "lib" / "generated" / "lucid.waypoint.ts"
)
HELIOS_TS_PATH = (
    ROOT / "apps" / "demo" / "src" / "lib" / "generated" / "lucid.helios.ts"
)


def main() -> int:
    sys.path.insert(0, str(LUCID_PKG))
    yume_manifest = _load_manifest(
        module_name="yume_modal_example.model",
        extra_path=YUME_MODAL_EXAMPLE_SRC,
    )
    waypoint_manifest = _load_manifest(
        module_name="waypoint_modal_example.model",
        extra_path=WAYPOINT_MODAL_EXAMPLE_SRC,
    )
    helios_manifest = _load_manifest(
        module_name="helios_modal_example.model",
        extra_path=HELIOS_MODAL_EXAMPLE_SRC,
    )
    MANIFEST_PATH.parent.mkdir(parents=True, exist_ok=True)
    MANIFEST_PATH.write_text(
        json.dumps(yume_manifest, indent=2, sort_keys=True) + "\n",
        encoding="utf-8",
    )
    WAYPOINT_MANIFEST_PATH.write_text(
        json.dumps(waypoint_manifest, indent=2, sort_keys=True) + "\n",
        encoding="utf-8",
    )
    HELIOS_MANIFEST_PATH.write_text(
        json.dumps(helios_manifest, indent=2, sort_keys=True) + "\n",
        encoding="utf-8",
    )
    TS_PATH.parent.mkdir(parents=True, exist_ok=True)
    TS_PATH.write_text(render_ts(yume_manifest), encoding="utf-8")
    WAYPOINT_TS_PATH.write_text(render_ts(waypoint_manifest), encoding="utf-8")
    HELIOS_TS_PATH.write_text(render_ts(helios_manifest), encoding="utf-8")
    return 0


def _load_manifest(*, module_name: str, extra_path: Path) -> dict[str, Any]:
    if str(extra_path) not in sys.path:
        sys.path.insert(0, str(extra_path))

    lucid = importlib.import_module("lucid")
    module = importlib.import_module(module_name)
    class_name = next(
        name
        for name, value in module.__dict__.items()
        if isinstance(value, type)
        and getattr(value, "__module__", None) == module_name
        and name.endswith("LucidModel")
    )
    model_cls = getattr(module, class_name)
    return lucid.build_model_definition(model_cls).to_manifest()


def render_ts(manifest: dict[str, Any]) -> str:
    input_interfaces: list[str] = []
    input_map_lines: list[str] = []
    input_names: list[str] = []
    for input_spec in manifest.get("inputs", []):
        name = str(input_spec["name"])
        input_names.append(name)
        interface_name = _interface_name(name)
        input_interfaces.append(
            f"export interface {interface_name} {render_object_schema(input_spec.get('args_schema', {}))}"
        )
        input_map_lines.append(f'  "{name}": {interface_name}')

    manifest_json = json.dumps(manifest, indent=2, sort_keys=True)
    input_name_union = " | ".join(f'"{name}"' for name in input_names) or "never"
    return "\n".join(
        [
            "// This file is @generated by scripts/generate_lucid_artifacts.py.",
            "// Do not edit it by hand.",
            "",
            f"export const lucidManifest = {manifest_json} as const",
            "",
            "export type HoldInputBinding = {",
            '  kind: "hold"',
            "  keys: string[]",
            "  mouse_buttons: number[]",
            "}",
            "",
            "export type PressInputBinding = {",
            '  kind: "press"',
            "  keys: string[]",
            "  mouse_buttons: number[]",
            "}",
            "",
            "export type AxisInputBinding = {",
            '  kind: "axis"',
            "  positive_keys: string[]",
            "  negative_keys: string[]",
            "}",
            "",
            "export type PointerInputBinding = {",
            '  kind: "pointer"',
            "  pointer_lock: boolean",
            "}",
            "",
            "export type WheelInputBinding = {",
            '  kind: "wheel"',
            "  step: number",
            "}",
            "",
            "export type InputBinding =",
            "  | HoldInputBinding",
            "  | PressInputBinding",
            "  | AxisInputBinding",
            "  | PointerInputBinding",
            "  | WheelInputBinding",
            "",
            *input_interfaces,
            "",
            "export interface InputArgumentsByName {",
            *input_map_lines,
            "}",
            "",
            f"export type InputName = {input_name_union}",
            "",
            "export interface InputEnvelope<TName extends InputName = InputName> {",
            '  type: "action"',
            "  seq: number",
            "  ts_ms: number",
            "  session_id: string | null",
            "  payload: {",
            "    name: TName",
            "    args: InputArgumentsByName[TName]",
            "  }",
            "}",
            "",
            "const encoder = new TextEncoder()",
            "",
            "export function encodeInputMessage<TName extends InputName>(args: {",
            "  name: TName",
            "  args: InputArgumentsByName[TName]",
            "  seq: number",
            "  sessionId: string",
            "}) {",
            "  const envelope: InputEnvelope<TName> = {",
            '    type: "action",',
            "    seq: args.seq,",
            "    ts_ms: Date.now(),",
            "    session_id: args.sessionId,",
            "    payload: {",
            "      name: args.name,",
            "      args: args.args,",
            "    },",
            "  }",
            "  return encoder.encode(JSON.stringify(envelope))",
            "}",
            "",
        ]
    )


def render_object_schema(schema: dict[str, Any]) -> str:
    properties = schema.get("properties", {})
    required = set(schema.get("required", []))
    lines = ["{"]
    for key, value in properties.items():
        optional = "" if key in required else "?"
        lines.append(f"  {json.dumps(key)}{optional}: {_ts_type(value)}")
    lines.append("}")
    return "\n".join(lines)


def _ts_type(schema: dict[str, Any]) -> str:
    schema_type = schema.get("type")
    if isinstance(schema_type, list):
        return " | ".join(
            sorted(
                _ts_type({"type": item, **{k: v for k, v in schema.items() if k != "type"}})
                for item in schema_type
            )
        )
    if schema_type == "string":
        enum_values = schema.get("enum")
        if enum_values:
            return " | ".join(json.dumps(value) for value in enum_values)
        return "string"
    if schema_type in {"number", "integer"}:
        return "number"
    if schema_type == "boolean":
        return "boolean"
    if schema_type == "array":
        return f"{_ts_type(schema.get('items', {}))}[]"
    if schema_type == "null":
        return "null"
    return "Record<string, unknown>"


def _interface_name(action_name: str) -> str:
    sanitized = re.sub(r"[^A-Za-z0-9]+", " ", action_name)
    parts = [part for part in sanitized.split() if part]
    return "".join(part[:1].upper() + part[1:] for part in parts) + "Args"


if __name__ == "__main__":
    raise SystemExit(main())
