apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "lucid-runtime.coordinator.fullname" . }}
  labels:
    {{- include "lucid-runtime.labels" . | nindent 4 }}
    app.kubernetes.io/component: coordinator
spec:
  replicas: {{ .Values.coordinator.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/instance: {{ .Release.Name }}
      app.kubernetes.io/component: coordinator
  template:
    metadata:
      labels:
        app.kubernetes.io/instance: {{ .Release.Name }}
        app.kubernetes.io/component: coordinator
    spec:
      containers:
        - name: coordinator
          image: "{{ .Values.coordinator.image.repository }}:{{ .Values.coordinator.image.tag }}"
          imagePullPolicy: {{ .Values.coordinator.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.coordinator.service.port }}
              protocol: TCP
          {{- with .Values.coordinator.command }}
          command:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.coordinator.env }}
          env:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          resources:
            {{- toYaml .Values.coordinator.resources | nindent 12 }}
